CREATE TABLE top_20_companies (
    id INT  NOT NULL ,
    timestamp DATE  NOT NULL ,
    company VARCHAR  NOT NULL ,
    level VARCHAR,
    title VARCHAR  NOT NULL ,
    totalyearlycompensation INT  NOT NULL ,
    location VARCHAR  NOT NULL ,
    yearsofexperience float  NOT NULL ,
    yearsatcompany float  NOT NULL ,
    tag VARCHAR,
    gender VARCHAR,
    cityid int  NOT NULL ,
    dmaid float  NOT NULL ,
    rownumber int  NOT NULL ,
    mastersdegree BOOLEAN  NOT NULL ,
    bachelorsdegree BOOLEAN  NOT NULL ,
    doctoratedegree BOOLEAN  NOT NULL ,
    raceasian BOOLEAN  NOT NULL ,
    racewhite BOOLEAN  NOT NULL ,
    racetwoormore BOOLEAN  NOT NULL ,
    raceblack BOOLEAN  NOT NULL ,
    racehispanic BOOLEAN  NOT NULL
)